name: bindgo
description: Use Dart to call Shell, complete the work of compiling Golang CGO code into a so, dll, a, WASM, and etc. And place it in the corresponding source file directory of each Flutter platform.
version: 0.1.2
homepage: https://github.com/ggdream/bindgo

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  process_run: ^0.12.2+1
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.18.2
